### ISSUE TITLE
PHP Notice Error

### ISSUE THREAD

**Issue by tabkad12** [razorpay/razorpay-cscart#23]
`2021/03/20 01:34:05 [error] 28189#28189: *179 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: is_hosted in /var/www/html/dev05.bigstorez.com/app/payments/razorpay/RazorpayPayment.php on line 36" while reading response header from upstream, client: 188.51.230.8, server: dev05.bigstorez.com, request: "GET /index.php?dispatch=checkout.process_payment HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "dev05.bigstorez.com", referrer: "https://dev05.bigstorez.com/checkout/"
`

We are receiving PHP notice under the web server error logs. Any help or guidance in this will be really appreciated.

CS-Cart Version: 4.12.2
Razorpay Version - 1.3-2.0

**Comment by ramth05** [comment]
@tabkad12,  

Can you please confirm how you are using this plugin and if there are any steps to reproduce it.
 
To avoid this notice for now you can update the   `/var/www/html/dev05.bigstorez.com/app/payments/razorpay/RazorpayPayment.php on line 36` with this line 
`if((isset($fields['is_hosted']) === true) and ($fields['is_hosted']))`

**Comment by tabkad12** [comment]
Thanks a ton, It worked as a charm.

**Comment by tabkad12** [comment]
After doing the mentioned change, we are not able to make the payment work from mobile devices but working fine with Desktop.

Please your kind guidance will be really appreciated.

![WhatsApp Image 2021-03-24 at 6 35 46 PM](https://user-images.githubusercontent.com/27804355/112341841-d20cb100-8cd2-11eb-9eb5-6c199b920277.jpeg)

**Comment by ramth05** [comment]
> mobile devices but working fine with Desktop.

@tabkad12 , I am not sure but don't see this could be the reason for the payments failing on mobile devices. I just tried and it's working fine.

**Comment by tabkad12** [comment]
Hi ramth05;

It is really strange, something which was working earlier now it is not working. I reverted the two changes which I had done in the Razorpay plugin, but still the same issue.

The two changes are as follows;

`    echo $razorpayPayment->getButton();
    }
    else
    {`
The above changes was done in /var/www/dev05../app/payments/razorpay.php to remove the submit form step.

Second change was the one which we are discussing;

changes in var/www/dev05../payments/razorpay/RazorPay.php in line 36;
'if((isset($fields['is_hosted']) === true) and ($fields['is_hosted']))'


Please your kind support will be really appreciated as we have a launch date nearing by.

I am attaching my plugins files in this thread for your kind reference...
[Razorpay-Deployed.zip](https://github.com/razorpay/razorpay-cscart/files/6202372/Razorpay-Deployed.zip)

**Comment by ramth05** [comment]
> Hi ramth05;
> 
> It is really strange, something which was working earlier now it is not working. I reverted the two changes which I had done in the Razorpay plugin, but still the same issue.
> 
> The two changes are as follows;
> 
> ` echo $razorpayPayment->getButton(); } else {`
> The above changes was done in /var/www/dev05../app/payments/razorpay.php to remove the submit form step.
> 
> Second change was the one which we are discussing;
> 
> changes in var/www/dev05../payments/razorpay/RazorPay.php in line 36;
> 'if((isset($fields['is_hosted']) === true) and ($fields['is_hosted']))'
> 
> Please your kind support will be really appreciated as we have a launch date nearing by.
> 
> I am attaching my plugins files in this thread for your kind reference...
> [Razorpay-Deployed.zip](https://github.com/razorpay/razorpay-cscart/files/6202372/Razorpay-Deployed.zip)

@tabkad12 , Please confirm if currently it's giving error ? Because morning I had placed one order without any issue from mobile.

**Comment by tabkad12** [comment]
There are certain incomplete transactions which comes when we face the same error message.

i have attached the screenshot for incomplete orders and screen recording from mobile facing that error.


Video Link:

https://www.dropbox.com/s/yq49glw2khtaoa8/IMG_7640.MP4?dl=0



<img width="706" alt="D71C4F28-874D-4594-8752-AF4DF7139A61" src="https://user-images.githubusercontent.com/27804355/112431513-b0eaa580-8d50-11eb-8bef-fb72074f1261.png">

**Comment by tabkad12** [comment]
Hi Ramth05,

please any luck going through our files why it is not working. It is still the same. Just FYKI, it is not working only on Iphones. Android mobiles are working perfectly. IPads, iMacs, desktop everything is working fine.

please your kind support and co-operation will be highly appreciated.

thanks..

**Comment by tabkad12** [comment]
We are getting the following error when we are doing transaction through iPhone, but we don't get this error when we try to do the same with other devices.
===================================================================================

2021/04/04 13:33:05 [error] 28189#28189: *12764 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: razorpay_order_id in /var/www/html/abcd.com/app/payments/razorpay/RazorpayPayment.php on line 122
PHP message: PHP Notice:  Undefined index: merchant_order_id in /var/www/html/abcd.com/app/payments/razorpay/RazorpayPayment.php on line 124" while reading upstream, client: 159.0.226.158, server: dev05.bigstorez.com, request: "POST /index.php?dispatch=payment_notification.return&payment=razorpay HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "dev05.bigstorez.com", referrer: "https://api.razorpay.com/"
2021/04/04 13:35:17 [error] 28189#28189: *12791 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: is_hosted in /var/www/html/dev05.bigstorez.com/app/payments/razorpay/RazorpayPayment.php on line 36" while reading response header from upstream, client: 159.0.226.158, server: www.abcd.com, request: "GET /index.php?dispatch=checkout.process_payment&clicked=true HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "dev05.bigstorez.com", referrer: "https://www.abcd.com/index.php?dispatch=checkout.process_payment"
2021/04/04 13:35:35 [error] 28189#28189: *12791 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: razorpay_order_id in /var/www/html/abcd.com/app/payments/razorpay/RazorpayPayment.php on line 122
PHP message: PHP Notice:  Undefined index: merchant_order_id in /var/www/html/abcd.com/app/payments/razorpay/RazorpayPayment.php on line 124" while reading upstream, client: 159.0.226.158, server: abcd.com, request: "POST /index.php?dispatch=payment_notification.return&payment=razorpay HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "dev05.bigstorez.com", referrer: "https://api.razorpay.com/"



==================================================================================

**Comment by ayush-razorpay** [comment]
@tabkad12, I tried replicating the issue with the ios emulator but I didn't encounter this after trying multiple times.


<img src="https://user-images.githubusercontent.com/78246948/114496167-fe19b300-9c3c-11eb-936e-2ce68fb7d2a7.png" data-canonical-src="https://user-images.githubusercontent.com/78246948/114496167-fe19b300-9c3c-11eb-936e-2ce68fb7d2a7.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/78246948/114495854-7469e580-9c3c-11eb-933d-a51b37c92cca.png" data-canonical-src="https://user-images.githubusercontent.com/78246948/114495854-7469e580-9c3c-11eb-933d-a51b37c92cca.png" width="200" height="400" />


Is this issue specific to a device?  did we check with other ios devices?

**Comment by tabkad12** [comment]
Hi Ayush,

I have shared the video directly from an IOS iPhone. Also I mentioned that
it works perfectly fine with iPads or iMacs, Desktop and Android. The issue
is on iPhones, We have tests on iPhone X, iPhone XS, iPhone 12 and iPhone
8. Please share with me the working video from either of these iPhone
models.

**Comment by tabkad12** [comment]
Hi Ayush,

A kind and humble reminder.

**Comment by ayush-razorpay** [comment]
@tabkad12, we respect and appreciate your patience.  

Was able to replicate the issue on iPhone 12.

Please rest assured, we are getting this checked on priority and will keep you updated.

**Comment by tabkad12** [comment]
@ayush-razorpay : Looking forward to your swift response.

**Comment by ayush-razorpay** [comment]
@tabkad12, can you please confirm if we using 3rd party theme here?

**Comment by tabkad12** [comment]
We are using Unitheme.

**Comment by ayush-razorpay** [comment]
hi @tabkad12, upon further investigation of the issue we found that PHP sessions are not working with the above-stated devices with respect to Razorpay Checkout.
Our product team is working on it.
But, the challenge at our end is that we are not yet sure how big the needed fix would be.

We respect your patience and please rest assured we will get this resolved. 

There is an anticipated delay here, due to the nature of this issue.
Will keep you posted. Thanks for bearing with us. :)

**Comment by tabkad12** [comment]
Thanks Ayush for your response.

Hope that the fix comes soon, before our store launch date. Keeping fingers crossed.

I tried the same with the basic theme also, but still the same issue.
[RPReplay_Final1619109562.mp4.zip](https://github.com/razorpay/razorpay-cscart/files/6359957/RPReplay_Final1619109562.mp4.zip)

**Comment by ayush-razorpay** [comment]
@tabkad12 , This is fixed .

**Comment by tabkad12** [comment]
Do i have to do any changes on our end to make it work?

![C3F2D01C-54A5-4FF6-969D-6FBD4C8FA97A](https://user-images.githubusercontent.com/27804355/118970884-6ca60b00-b977-11eb-9c9b-965fe6ecc2cd.jpeg)

**Comment by ayush-razorpay** [comment]
@tabkad12 , apologies here. We had identified an issue with the beta release. The same is rolled back for now.
We respect your patience here.  Will update you ASAP

**Comment by ayush-razorpay** [comment]
@tabkad12 , we have just released a new version with the required fix.

https://github.com/razorpay/razorpay-cscart/releases/tag/1.3.2

Please update to the latest release .

**Comment by tabkad12** [comment]
It worked with the mobile but unfortunately i am getting error from desktop. Please find the attached for your kind reference.
![razorpay_desktop_error](https://user-images.githubusercontent.com/27804355/121302970-28b57e80-c903-11eb-84cc-01d469c7f0c7.PNG)

**Comment by tabkad12** [comment]
``

**Comment by ayush-razorpay** [comment]
https://user-images.githubusercontent.com/78246948/121307630-cddd5080-c91d-11eb-9b60-86babd8c7aba.mp4

@tabkad12  we tried this on local setup, and it's working at our end.  Can you please check if some other plugin is causing this at your end?

**Comment by tabkad12** [comment]
Hi Ayush,

Yes, there was an issue with a Twig Template which was giving that error. Not related with the plugins provided by you.

Now it is working fine with the new plugin files.

Thanks for your kind efforts.

**Comment by ayush-razorpay** [comment]
Thanks for the update @tabkad12
